version: "3"
services:
  leonard-frontend-stage:
    container_name: leonard-frontend-stage
    #    restart: always
    build: .
    #command: bash -c "script.sh"
  #  networks:
   #   nobelpage-frontend-stage:
    #    ipv4_address: 172.60.0.2
    volumes:
      - ./:/var/www/html/
  #  ports:
   #   - "5034:80"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
#Docker Networks
#networks:
 # nobelpage-frontend-stage:
  #  external: true
networks:
  default:
    external: true
    name: npm-nw

