trigger: none

 
pool: 
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: Hohermarkt/Pipelines  # Change this to the actual repo
      ref: refs/heads/main  # Change branch if needed

stages:
- stage: BuildStage
  jobs:
  - job:
    displayName: Build frontend image
    workspace:
        clean: all
    steps:
    - template: /pipelines/CI/ci.yaml@Pipelines
      # parameters:
      #   dockerFile: Dockerfile
      #   buildContext: $(Build.SourcesDirectory)
      #   repository: spectory-reability-main

- stage: DeployStage
  jobs:
  - job:
    displayName: Deploy frontend image
    workspace:
        clean: all
    steps:
    - template: /pipelines/CD/cd.yaml@Pipelines
      parameters:
        WebAppName: 'app-reability'
        DockerNamespaceName: 'acrreability'