trigger: none

pool: 
  vmImage: 'ubuntu-latest'

variables:
  DockerNamespaceName: 'acrreability'

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: Hohermarkt/Pipelines  # Change this to the actual repo
      ref: refs/heads/main  # Change branch if needed

stages:
- stage: BuildStage
  jobs:
  - job:
    displayName: Build frontend image
    workspace:
        clean: all
    steps:
    - template: /pipelines/CI/ci.yaml@Pipelines
      # parameters:
      #   dockerFile: Dockerfile
      #   buildContext: $(Build.SourcesDirectory)
      #   repository: spectory-reability-main

- stage: DeployStage
  jobs:
  - job:
    displayName: Deploy frontend image
    workspace:
        clean: all
    steps:
    - script: |
        if [ "$(Build.SourceBranchName)" == "demo-env" ]; then
          echo "##vso[task.setvariable variable=WebAppName]demo-reability"
        elif [ "$(Build.SourceBranchName)" == "us-env" ]; then
          echo "##vso[task.setvariable variable=WebAppName]us-reability"
        elif [ "$(Build.SourceBranchName)" == "app-env" ]; then
          echo "##vso[task.setvariable variable=WebAppName]app-reability"
        fi
      displayName: 'Set WebAppName Variable'
    - template: /pipelines/CD/cd.yaml@Pipelines
      parameters:
        WebAppName: $(WebAppName)
        DockerNamespaceName: $(DockerNamespaceName)
